(function(root,factory){if(typeof module!=='undefined')module.exports=factory();else root.FitnessGame=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const names={chest:'胸部',arms:'手臂',core:'腹部',legs:'腿部',water:'喝水',protein:'蛋白粉',sleep:'睡觉'};
const order=['chest','legs','arms','core','water','protein','sleep'];
function create(body){return{body:body==='thin'?'thin':'fat',phase:'training',elapsed:0,step:0,muscles:{chest:0,arms:0,core:0,legs:0},energy:100,heat:0,lastTap:-99,maintain:0,walk:0,message:'跟着教练，点击发光部位',reason:'',events:0,combo:0,tiles:0,score:42};}
function expected(s){return order[s.step%order.length];}
function fail(s,r){s.phase='failed';s.reason=r;s.message=r;}
function tick(s,dt){if(!['training','maintain','walk'].includes(s.phase))return;dt=Math.max(0,dt);s.elapsed+=dt;s.heat=Math.max(0,s.heat-dt*18);if(s.phase==='training'&&s.elapsed>=60)return fail(s,'30 天到了，还没有完成均衡训练');if(s.phase==='maintain'){s.maintain+=dt;if(s.maintain>=10){s.phase='walk';s.message='薄肌保持成功！点击脚印，走向她';}}if(s.phase==='walk'&&s.elapsed>=90)fail(s,'错过了见面时间，再练一次吧');}
function action(s,key){if(!['training','maintain','walk'].includes(s.phase))return false;if(s.phase==='walk'){if(key!=='walk')return false;s.walk++;s.combo++;if(s.walk>=6){s.phase='won';s.message='牵手成功！自律，也要懂得休息';}return true;}if(s.phase==='maintain'){if(key!=='water'&&key!=='sleep')return false;s.energy=Math.min(100,s.energy+(key==='water'?15:50));s.message=key==='water'?'保持住，补水成功':'呼噜……恢复满格';return true;}if(key==='water'||key==='protein'||key==='sleep'){s.energy=Math.min(100,s.energy+({water:15,protein:12,sleep:100}[key]));s.message=names[key]+'完成';if(key===expected(s)){s.step++;s.combo++;if(s.step>=42){s.phase='maintain';s.message='薄肌达成！保持 10 秒';}}return true;}if(key!==expected(s)){fail(s,'教练让你'+names[expected(s)]+'，你点错了！');return false;}s.events++;s.combo++;s.tiles=(s.tiles+3)%9;s.score=Math.min(100,42+s.events*2+s.combo);s.muscles[key]++;s.energy=Math.max(0,s.energy-12);s.message=names[key]+'训练完成！连击 '+s.combo; s.step++;if(s.step>=42){s.phase='maintain';s.message='薄肌达成！保持 10 秒';}return true;}
return{create,tick,action,expected,names};});
