(function(root,factory){if(typeof module!=='undefined')module.exports=factory();else root.FitnessGame=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const names={chest:'胸部',arms:'手臂',core:'腹部',legs:'腿部',water:'喝水',protein:'蛋白粉',sleep:'睡觉'};
const base=['chest','legs','arms','core','water','protein','sleep'];
function makePlan(){const p=[];for(let r=0;r<6;r++){const a=base.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}p.push(...a);}return p;}
function create(body){return{body:body==='thin'?'thin':'fat',phase:'training',elapsed:0,step:0,plan:makePlan(),muscles:{chest:0,arms:0,core:0,legs:0},energy:100,heat:0,progress:0,lastTap:-99,maintain:0,walk:0,message:'跟着教练，点击发光部位',reason:'',events:0,combo:0,tiles:0,score:0,active:false};}
function expected(s){return s.plan[s.step%s.plan.length];}
function fail(s,r){s.phase='failed';s.reason=r;s.message=r;}
function tick(s,dt){if(!['training','walk'].includes(s.phase))return;dt=Math.max(0,dt);s.elapsed+=dt;if(s.phase==='training'){if(s.active){s.score-=dt*0.35;s.progress=s.score;}if(s.active&&s.score<=0)return fail(s,'练废了：分数掉到0，重新安排训练吧');if(s.elapsed>=60){if(s.score>=70&&s.score<=80){s.phase='walk';s.message='薄肌达标！迎娶关卡已解锁';}else fail(s,'不够努力：美女不会爱上懒惰虫');}}}
function bodyType(s){return s.score<70?'original':s.score<=80?'lean':'thick';}
function action(s,key){if(!['training','maintain','walk'].includes(s.phase))return false;if(s.phase==='walk'){if(key!=='walk')return false;s.walk++;s.combo++;if(s.walk>=6){s.phase='won';s.message='牵手成功！自律，也要懂得休息';}return true;}if(s.phase==='maintain'){if(key!=='water'&&key!=='sleep')return false;s.energy=Math.min(100,s.energy+(key==='water'?15:50));s.message=key==='water'?'保持住，补水成功':'呼噜……恢复满格';return true;}if(key==='water'||key==='protein'||key==='sleep'){if(key!==expected(s)){s.active=true;s.active=true;s.score-=10;s.progress=s.score;s.message='点错了，分数 -10';if(s.score<=0)fail(s,'练废了：分数掉到0，重新安排训练吧');return true;}s.active=true;s.score+=s.score<70?4:1;s.progress=s.score;if(s.score>100){fail(s,'练成牛蛙了：肌肉太大，薄肌挑战失败');return true;}s.energy=Math.min(100,s.energy+({water:15,protein:12,sleep:100}[key]));s.message=names[key]+'完成！下一个提示出现';s.step++;s.combo++;return true;}if(key!==expected(s)){s.active=true;s.active=true;s.score-=10;s.progress=s.score;s.message='点错了，分数 -10';if(s.score<=0)fail(s,'练废了：分数掉到0，重新安排训练吧');return true;}s.active=true;s.score+=s.score<70?4:1;s.progress=s.score;if(s.score>100){fail(s,'练成牛蛙了：肌肉太大，薄肌挑战失败');return true;}s.events++;s.combo++;s.tiles=(s.tiles+3)%9;s.muscles[key]++;s.energy=Math.max(0,s.energy-12);s.message=names[key]+'训练完成！连击 '+s.combo; s.step++;return true;}
return{create,tick,action,expected,names,bodyType};});
