(function(root,factory){if(typeof module!=='undefined')module.exports=factory();else root.FitnessGame=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const names={chest:'胸部',arms:'手臂',core:'腹部',legs:'腿部',water:'喝水',protein:'蛋白粉',sleep:'睡觉'};
const base=['chest','legs','arms','core','water','protein','sleep'];
function makePlan(){const p=[];for(let r=0;r<6;r++){const a=base.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}p.push(...a);}return p;}
function create(body,skipTraining){return{body:body==='thin'?'thin':'fat',phase:skipTraining?'walk':'training',elapsed:skipTraining?30:0,step:0,plan:makePlan(),muscles:{chest:0,arms:0,core:0,legs:0},energy:100,heat:0,progress:0,lastTap:-99,maintain:0,walk:0,fallTaps:0,distance:0,beautyDistance:skipTraining?30:0,nextFoot:'left',velocity:0,onGround:true,message:'跟着教练，点击发光部位',lastAction:null,reason:'',events:0,combo:0,tiles:0,score:0,active:false};}
function expected(s){return s.plan[s.step%s.plan.length];}
function fail(s,r){s.phase='failed';s.reason=r;s.message=r;}
function startChase(s){s.phase='walk';s.distance=0;s.beautyDistance=30;s.walk=0;s.fallTaps=0;s.nextFoot='left';s.onGround=true;}
function gap(s){return Math.max(0,s.beautyDistance-s.distance);}
function tick(s,dt){if(!['training','walk','fallen'].includes(s.phase))return;dt=Math.max(0,dt);const before=s.elapsed;s.elapsed+=dt;if(s.phase==='walk'||s.phase==='fallen'){s.beautyDistance+=dt*5;if(gap(s)>80){fail(s,'失败了，下次会遇见更好的女人');}return;}if(s.active){s.score-=Math.min(dt,Math.max(0,60-before))*0.7;s.progress=s.score;}if(s.active&&s.score<=0)return fail(s,'练废了：分数掉到0，重新安排训练吧');if(s.elapsed>=30){if(s.score>=70&&s.score<=80){startChase(s);s.message='薄肌达标！交替点击追上她';}else fail(s,'不够努力：美女不会爱上懒惰虫');}}
function bodyType(s){return s.score<70?'original':s.score<=80?'lean':'thick';}
function action(s,key){if(!['training','maintain','walk','fallen'].includes(s.phase))return false;s.lastAction=key;if(s.phase==='fallen'){if(key!=='recover')return false;s.fallTaps++;s.message='爬起进度 '+s.fallTaps+'/10';if(s.fallTaps>=10){s.phase='walk';s.onGround=true;s.message='站起来了！继续左右交替追赶';}return true;}if(s.phase==='walk'){if(key!==s.nextFoot){s.onGround=false;s.velocity=0;s.phase='fallen';s.fallTaps=0;s.message='摔倒了！快速点击10下爬起来';return false;}s.onGround=true;s.walk++;s.distance++;s.velocity=6;s.combo++;s.nextFoot=s.nextFoot==='left'?'right':'left';if(s.distance>=s.beautyDistance){s.phase='won';s.message='追上她了！牵手成功';}return true;}if(s.phase==='maintain'){if(key!=='water'&&key!=='sleep')return false;s.energy=Math.min(100,s.energy+(key==='water'?15:50));s.message=key==='water'?'保持住，补水成功':'呼噜……恢复满格';return true;}if(key==='water'||key==='protein'||key==='sleep'){if(key!==expected(s)){s.active=true;s.active=true;s.score-=10;s.progress=s.score;s.message='点错了，分数 -10';if(s.score<=0)fail(s,'练废了：分数掉到0，重新安排训练吧');return true;}s.active=true;s.score+=s.score<70?2:0.5;s.progress=s.score;if(s.score>100){fail(s,'练成牛蛙了：肌肉太大，薄肌挑战失败');return true;}s.energy=Math.min(100,s.energy+({water:15,protein:12,sleep:100}[key]));s.message=names[key]+'完成！下一个提示出现';s.step++;s.combo++;return true;}if(key!==expected(s)){s.active=true;s.active=true;s.score-=10;s.progress=s.score;s.message='点错了，分数 -10';if(s.score<=0)fail(s,'练废了：分数掉到0，重新安排训练吧');return true;}s.active=true;s.score+=s.score<70?2:0.5;s.progress=s.score;if(s.score>100){fail(s,'练成牛蛙了：肌肉太大，薄肌挑战失败');return true;}s.events++;s.combo++;s.tiles=(s.tiles+3)%9;s.muscles[key]++;s.energy=Math.max(0,s.energy-12);s.message=names[key]+'训练完成！连击 '+s.combo; s.step++;return true;}
return{create,tick,action,expected,names,bodyType,gap};});
